USE [BDSWITCH]
GO

/****** Object:  Table [dbo].[DADOS_SWITCH]    Script Date: 11/12/2024 11:22:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DADOS_SWITCH](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COD_SAIDA] [varchar](50) NULL,
	[COD_OP] [varchar](255) NULL,
	[COD_OS] [varchar](255) NULL,
	[SKU] [varchar](255) NULL,
	[NOME_ARQUIVO] [varchar](100) NULL,
	[ESCOLA] [varchar](50) NULL,
	[TIRAGEM] [int] NULL,
	[PAGINACAO] [int] NULL,
	[REGIAO] [varchar](50) NULL,
	[SEGMENTO] [varchar](50) NULL,
	[ENSINO] [varchar](50) NULL,
	[TURNO] [varchar](50) NULL,
	[MODELO] [varchar](50) NULL,
	[MATERIAL] [varchar](50) NULL,
	[SEPARACAO] [int] NULL,
	[MIOLO_PAPEL] [varchar](50) NULL,
	[MIOLO_FORMATO] [varchar](50) NULL,
	[MIOLO_GRAMATURA] [varchar](50) NULL,
	[MIOLO_COR] [varchar](50) NULL,
	[CAPA_TIPO] [varchar](50) NULL,
	[ACABAMENTO1] [varchar](50) NULL,
	[REFILE] [char](10) NULL,
	[FORMATO_FINAL] [varchar](100) NULL,
	[MAQUINARIO] [varchar](50) NULL,
	[MARCA] [varchar](50) NULL,
	[DATA_SAIDA] [date] NULL,
	[DATA_ENTREGA] [date] NULL,
	PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


