-- CRIA A BASE DE DADOS 
CREATE DATABASE BDSWITCH;

-- USA O BANCO DE DADOS
USE BDSWITCH;

-- CRIA A TABLE
CREATE TABLE DADOS_SWITCH 
(
    ID INT PRIMARY KEY,
    COD_SAIDA VARCHAR(50) NOT NULL,
    COD_OP VARCHAR(50) NOT NULL,
    
    SKU VARCHAR(50) NOT NULL,
    NOME_ARQUIVO VARCHAR(100) NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    ESCOLA VARCHAR(50) NOT NULL,
    REGIAO VARCHAR(50) NOT NULL,
    
    TIRAGEM INT NOT NULL,
    
    SEGMENTO VARCHAR(50) NOT NULL,
    ENSINO VARCHAR(50) NOT NULL,
    TURNO VARCHAR(50) NOT NULL,
    MATERIAL VARCHAR(50) NOT NULL,
    
    SEPARACAO INT NOT NULL,
    
    MIOLO_PAPEL VARCHAR(50) NOT NULL,
    MIOLO_FORMATO VARCHAR(50) NOT NULL,
    MIOLO_GRAMATURA VARCHAR(50) NOT NULL,
    MIOLO_COR VARCHAR(50) NOT NULL,
    
    CAPA_TIPO VARCHAR(50) NOT NULL,
    
    ACABAMENTO1 VARCHAR(50) NOT NULL,
    REFILE CHAR(10) NOT NULL,
    
    FORMATO_FINAL CHAR(10) NOT NULL,
    MAQUINARIO VARCHAR(50) NOT NULL,
    
    DATA_SAIDA DATE NOT NULL,
    DATA_ENTREGA DATE NOT NULL,
);

