-- CRIA A BASE DE DADOS 
CREATE DATABASE BDSWITCH;

-- USA O BANCO DE DADOS
USE BDSWITCH;

-- CRIA A TABLE
CREATE TABLE DADOS_SWITCH 
(
    ID INT PRIMARY KEY IDENTITY(1,1),
    COD_SAIDA VARCHAR(50) NULL,
    COD_OP VARCHAR(50) NULL,
    SKU VARCHAR(50) NULL,
    NOME_ARQUIVO VARCHAR(100) NULL,
    MARCA VARCHAR(50) NULL,
    ESCOLA VARCHAR(50) NULL,
    REGIAO VARCHAR(50) NULL,
    TIRAGEM INT NULL,
    SEGMENTO VARCHAR(50) NULL,
    ENSINO VARCHAR(50) NULL,
    TURNO VARCHAR(50) NULL,
    MODELO VARCHAR(50) NULL,
    MATERIAL VARCHAR(50) NULL,
    SEPARACAO INT NULL,
    MIOLO_PAPEL VARCHAR(50) NULL,
    MIOLO_FORMATO VARCHAR(50) NULL,
    MIOLO_GRAMATURA VARCHAR(50) NULL,
    MIOLO_COR VARCHAR(50) NULL,
    CAPA_TIPO VARCHAR(50) NULL,
    ACABAMENTO1 VARCHAR(50) NULL,
    REFILE CHAR(10) NULL,
    FORMATO_FINAL CHAR(10) NULL,
    MAQUINARIO VARCHAR(50) NULL,
    DATA_SAIDA DATE NULL,
    DATA_ENTREGA DATE NULL
);

DROP TABLE DADOS_SWITCH
SELECT * FROM DADOS_SWITCH